In [205]:
import numpy as np
from sklearn import datasets as dt
import matplotlib.pyplot as plt

In [4]:
iris = dt.load_iris()

In [11]:
X = iris.data
Y = iris.target

In [210]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [17]:
len(Y)

150

In [29]:
X_train, Y_train, X_test, Y_test = X[:149], Y[:149], X[149:], Y[149:]

In [52]:
# X_train
# X_test
vs = np.sqrt(np.sum(np.square(np.subtract(X_train, X_test)), axis=1))
vs = np.sort(vs)
vs

array([ 0.28284271,  0.31622777,  0.33166248,  0.33166248,  0.36055513,
        0.37416574,  0.45825757,  0.46904158,  0.53851648,  0.53851648,
        0.58309519,  0.60827625,  0.6244998 ,  0.64031242,  0.64031242,
        0.64807407,  0.64807407,  0.65574385,  0.66332496,  0.67082039,
        0.67082039,  0.68556546,  0.72111026,  0.73484692,  0.73484692,
        0.75498344,  0.76157731,  0.76811457,  0.77459667,  0.78102497,
        0.79372539,  0.81240384,  0.83066239,  0.83666003,  0.83666003,
        0.86023253,  0.86023253,  0.8660254 ,  0.9486833 ,  0.9486833 ,
        0.9486833 ,  0.96436508,  0.99498744,  1.        ,  1.00498756,
        1.02956301,  1.04880885,  1.05356538,  1.06770783,  1.06770783,
        1.07238053,  1.08166538,  1.08627805,  1.08627805,  1.09087121,
        1.1       ,  1.11355287,  1.12249722,  1.12249722,  1.14017543,
        1.15325626,  1.15758369,  1.17473401,  1.17898261,  1.24096736,
        1.24498996,  1.25299641,  1.25698051,  1.27279221,  1.28

In [87]:
def CalculateEucledianDistance(X_train, X_test):
    euc = np.sqrt(np.sum(np.square(np.subtract(X_train, X_test)), axis=1))
#     euc = np.sort(euc)
    
    return euc

In [88]:
Y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [156]:
eucdist = CalculateEucledianDistance(X_train, X_test)
sorteucdist = np.sort(eucdist)
sorteucdist

array([ 0.28284271,  0.31622777,  0.33166248,  0.33166248,  0.36055513,
        0.37416574,  0.45825757,  0.46904158,  0.53851648,  0.53851648,
        0.58309519,  0.60827625,  0.6244998 ,  0.64031242,  0.64031242,
        0.64807407,  0.64807407,  0.65574385,  0.66332496,  0.67082039,
        0.67082039,  0.68556546,  0.72111026,  0.73484692,  0.73484692,
        0.75498344,  0.76157731,  0.76811457,  0.77459667,  0.78102497,
        0.79372539,  0.81240384,  0.83066239,  0.83666003,  0.83666003,
        0.86023253,  0.86023253,  0.8660254 ,  0.9486833 ,  0.9486833 ,
        0.9486833 ,  0.96436508,  0.99498744,  1.        ,  1.00498756,
        1.02956301,  1.04880885,  1.05356538,  1.06770783,  1.06770783,
        1.07238053,  1.08166538,  1.08627805,  1.08627805,  1.09087121,
        1.1       ,  1.11355287,  1.12249722,  1.12249722,  1.14017543,
        1.15325626,  1.15758369,  1.17473401,  1.17898261,  1.24096736,
        1.24498996,  1.25299641,  1.25698051,  1.27279221,  1.28

In [165]:
indexes = np.arange(len(Y_train))
dictionary = {k : v for k, v in zip(eucdist, indexes)}
dictionary

{0.28284271247461801: 127,
 0.31622776601683766: 138,
 0.33166247903553997: 142,
 0.3605551275463989: 70,
 0.37416573867739383: 83,
 0.45825756949558422: 121,
 0.46904157598234281: 126,
 0.53851648071344971: 123,
 0.53851648071345015: 133,
 0.5830951894845301: 113,
 0.60827625302982147: 63,
 0.62449979983983983: 111,
 0.64031242374328468: 147,
 0.6403124237432849: 114,
 0.64807406984078575: 103,
 0.64807406984078619: 137,
 0.65574385243019973: 146,
 0.66332495807107972: 110,
 0.67082039324993625: 56,
 0.67082039324993681: 91,
 0.6855654600401041: 78,
 0.7211102550927978: 116,
 0.73484692283495301: 72,
 0.73484692283495345: 66,
 0.75498344352707458: 85,
 0.76157731058639078: 115,
 0.76811457478686085: 148,
 0.77459666924148296: 73,
 0.78102496759066531: 134,
 0.7937253933193773: 128,
 0.81240384046359582: 77,
 0.83066238629180733: 55,
 0.83666002653407534: 84,
 0.83666002653407567: 132,
 0.86023252670426253: 54,
 0.86602540378443837: 119,
 0.94868329805051332: 61,
 0.94868329805051343: 

In [201]:
k=10
karray = sorteucdist[:k]
karray

array([ 0.28284271,  0.31622777,  0.33166248,  0.33166248,  0.36055513,
        0.37416574,  0.45825757,  0.46904158,  0.53851648,  0.53851648])

In [202]:
classes = []
for i in karray:
    index = dictionary[i]
    classes.append(Y_train[index])

classes

[2, 2, 2, 2, 1, 1, 2, 2, 2, 2]

In [209]:
unique, counts = np.unique(classes, return_counts=True)
'''class_dictionary = dict(zip(unique, counts))
np.max(class_dictionary)'''

'class_dictionary = dict(zip(unique, counts))\nnp.max(class_dictionary)'

In [99]:
mineucdist = np.min(karray)
mineucdist

0.28284271247461801

In [127]:
a = Y_train[[index for index, dist in dictionary.items() if dist == mineucdist]]
print(a)

[2]


In [186]:
def predict(X_train, Y_train, X_test, k):
    
    eucdist = CalculateEucledianDistance(X_train, X_test)
    sorteucdist = np.sort(eucdist)
    
    indexes = np.arange(len(Y_train))
    dictionary = {k : v for k, v in zip(eucdist, indexes)}
    
    karray = sorteucdist[:k]
    
#     minecudist = np.min(karray)
    classes = []
    for i in karray:
        index = dictionary[i]
        classes.append(Y_train[index])

#     predicted_class = Y_train[[index for index, dist in dictionary.items() if dist == mineucdist]]
    unique, counts = np.unique(classes, return_counts=True)
    counter = 0
    predicted_class = 0
    for i in range(len(unique)):
        if counts[i]>counter:
            predicted_class = unique[i]
        
    
    return predicted_class
    

In [191]:
k=30
pc = predict(X_train, Y_train, X_test, k)

In [192]:
pc

2

In [204]:
Y_test

array([2])